# Generated by Django 4.1.3 on 2022-11-16 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lighting', models.IntegerField(default=3)),
                ('sound', models.IntegerField(default=3)),
                ('traffic', models.IntegerField(default=3)),
                ('vegan', models.BooleanField()),
                ('gluten_free', models.BooleanField()),
                ('lactose_free', models.BooleanField()),
                ('service', models.IntegerField(default=3)),
                ('wifi', models.BooleanField()),
                ('outlets', models.BooleanField()),
                ('patio', models.BooleanField()),
                ('pet_friendly', models.BooleanField()),
                ('comments', models.TextField(max_length=250)),
                ('cafe_id', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('image_url', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
