# Generated by Django 4.1.3 on 2022-11-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='airconditioning',
            new_name='gluten_free',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='drinks',
            new_name='lactose_free',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='food',
            new_name='vegan',
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='lighting',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='sound',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='traffic',
            field=models.IntegerField(),
        ),
    ]
